In [1]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi its
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi its
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

In [1]:
import pandas as pd

data_frame = pd.read_csv('riyasewana_vehicles.csv')
data_frame.head()

,Vehicle Type,Make,Model,Year,Price,Milleage,District,published date,Vehicle URL
0,Pickup,Mitsubishi,L200 Sportero,2015.0,"Rs. 12,250,000",3.0,Kadawatha,2026-02-06,https://riyasewana.com/buy/mitsubishi-l200-spo...
1,Three Wheel,Bajaj,4 Stroke,2010.0,"Rs. 1,280,000",111111.0,Gampaha,2026-01-31,https://riyasewana.com/buy/bajaj-4-stroke-sale...
2,Car,Toyota,Axio,2008.0,"Rs. 7,150,000",178000.0,Colombo,2026-02-01,https://riyasewana.com/buy/toyota-axio-sale-co...
3,Van,Suzuki,Every Join,2024.0,"Rs. 7,400,000",12300.0,Colombo,2026-02-06,https://riyasewana.com/buy/suzuki-every-join-s...
4,Pickup,Toyota,Hilux Invicible D4,2007.0,"Rs. 10,200,000",170000.0,Gampaha,2026-02-07,https://riyasewana.com/buy/toyota-hilux-invici...

In [2]:
list(data_frame.columns)

['Vehicle Type',
 'Make',
 'Model',
 'Year',
 'Price',
 'Milleage',
 'District',
 'published date',
 'Vehicle URL']

In [3]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80006 entries, 0 to 80005
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Vehicle Type    79304 non-null  object
 1   Make            80006 non-null  object
 2   Model           79967 non-null  object
 3   Year            79923 non-null  float64
 4   Price           80006 non-null  object
 5   Milleage        67779 non-null  float64
 6   District        80001 non-null  object
 7   published date  80006 non-null  object
 8   Vehicle URL     80006 non-null  object
dtypes: float64(2), object(7)
memory usage: 5.5+ MB

In [4]:
data_frame.describe()

               Year      Milleage
count  79923.000000  6.777900e+04
mean    2010.284436  6.696134e+05
std       10.610826  3.946626e+07
min     1900.000000  1.000000e+00
25%     2006.000000  3.172000e+04
50%     2013.000000  7.342100e+04
75%     2017.000000  1.410000e+05
max     2026.000000  8.888889e+09

In [12]:
!wmic cpu get name,NumberOfCores,NumberOfLogicalProcessors,MaxClockSpeed

MaxClockSpeed  Name                                       NumberOfCores  NumberOfLogicalProcessors

2496           Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz  4              8

In [13]:
data_frame.describe(include='object')

,Vehicle Type,Make,Model,Price,District,published date,Vehicle URL
count,79304,80006,79967,80006,80001,80006,80006
unique,9,130,10793,2820,115,91,66652
top,Car,Toyota,CT-100,Negotiable,Colombo,2026-02-07,https://riyasewana.com/buy/mitsubishi-outlande...
freq,27578,14900,1920,15819,7612,6190,185